---
title: "B_Corps"
author: "Peijin Li"
date: "2022-12-14"
output: html_document
---

```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE)
## import libraries 
#install.packages("devtools")
library(devtools)
#install_github("kassambara/easyGgplot2")
#install.packages("gridExtra")    
library(tidyverse)
library(knitr)
library(ggplot2)
library(dplyr)
library(scales)
library(easyGgplot2)
library("gridExtra") 
library(plyr)
library(data.table)
library(maps)
```

```{r, warning=FALSE, message=FALSE}
## prepare data 
industry_0 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/industry_0.csv")

ggplot(data = industry_0, aes(x = reorder(index,-industry_category), y = industry_category)) +
  geom_bar(stat = "identity")+
  labs(x="Industry Category", y="Count",
       title="B Corp Cluster 1 Industry Category")+   
  geom_text(aes(label=scales::comma(round(industry_category,digits = 0))),hjust =0.5,vjust=-0.5, size=3.5,position = position_dodge(width= 1))+
  ylim(0,300)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r, warning=FALSE, message=FALSE}
## prepare data 
industry_1 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/industry_1.csv")

ggplot(data = industry_1, aes(x = reorder(index,-industry_category), y = industry_category)) +
  geom_bar(stat = "identity")+
  labs(x="Industry Category", y="Count",
       title="B Corp Cluster 2 Industry Category")+   
  geom_text(aes(label=scales::comma(round(industry_category,digits = 0))),hjust =0.5,vjust=-0.5, size=3.5,position = position_dodge(width= 1))+
  ylim(0,1000)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r, warning=FALSE, message=FALSE}
## prepare data 
industry_2 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/industry_2.csv")

ggplot(data = industry_2, aes(x = reorder(index,-industry_category), y = industry_category)) +
  geom_bar(stat = "identity")+
  labs(x="Industry Category", y="Count",
       title="B Corp Cluster 3 Industry Category")+   
  geom_text(aes(label=scales::comma(round(industry_category,digits = 0))),hjust =0.5,vjust=-0.5, size=3.5,position = position_dodge(width= 1))+
  ylim(0,500)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

Geographic map 
```{r, warning=FALSE, message=FALSE}
wm <- map_data("world") %>% filter(region != "Antarctica") 
  
## prepare data 
country_0 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/country_0.csv")
country_1 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/country_1.csv")
country_2 <- read_csv("D:/GU_peijin/GU_thrid semester/DS_III/final_project/country_2.csv")
# marge the state data with the election data 
dis0 <- left_join(countries, country_0, by = c("region"="index"))
dis1 <- left_join(countries, country_1, by = c("region"="index"))
dis2 <- left_join(countries, country_2, by = c("region"="index"))
```

Cluster 1 
```{r}

dis0 %>% 
  ggplot(aes(fill = country, map_id = region))+
  geom_map(map = world_map) +
  geom_polygon(data = wm, aes(x = long,y = lat, group = group),
               color = "grey47", fill = NA)+
  expand_limits(x = wm$long, y = wm$lat) +
  scale_fill_continuous(low="lightsteelblue3", high="darkred", 
                       guide="colorbar",na.value="white")+
  labs(fill='B Corp Number')+
  coord_fixed()+
   theme_void()
```

Cluster 2
```{r}
dis1 %>% 
  ggplot(aes(fill = country, map_id = region))+
  geom_map(map = world_map) +
  geom_polygon(data = wm, aes(x = long,y = lat, group = group),
               color = "grey47", fill = NA)+
  expand_limits(x = wm$long, y = wm$lat) +
  scale_fill_continuous(low="lightsteelblue3", high="darkred", 
                       guide="colorbar",na.value="white")+
  labs(fill='B Corp Number')+
  coord_fixed()+
   theme_void()
```

Cluster 3
```{r}
dis2 %>% 
  ggplot(aes(fill = country, map_id = region))+
  geom_map(map = world_map) +
  geom_polygon(data = wm, aes(x = long,y = lat, group = group),
               color = "grey47", fill = NA)+
  expand_limits(x = wm$long, y = wm$lat) +
  scale_fill_continuous(low="lightsteelblue3", high="darkred", 
                       guide="colorbar",na.value="white")+
  labs(fill='B Corp Number')+
  coord_fixed()+
   theme_void()
```



